Repository operate-first/operate-first-data-science-community, pull requests merged in 2021-11, with the labels that each got.

#2 add topic submission issue template
  .github/ISSUE_TEMPLATE/topic_submission.md
Labels: size/S

#3 Update README.md
  README.md
  docs/content.md
  docs/meetup-landing-page.md
Labels: size/M

#6 Add OWNERS
  OWNERS
Labels: size/XS

#7 Add mailing list
  README.md
  docs/meetup-landing-page.md
Labels: size/S, approved

#8 Update content.md
  docs/content.md
Labels: size/S, approved, lgtm

#9 update agenda add new calendar links
  docs/content.md
  docs/meetup-landing-page.md
Labels: size/M, approved, lgtm

#11 Update agenda
  docs/content.md
Labels: size/S, approved
