Repository operate-first/operate-first-data-science-community, pull requests merged in 2022-05, with the labels that each got.

#92 Meetup11 slides
  docs/content/opfmeetup11.pdf
Labels: size/XS, approved, lgtm

#93 Update agenda with video for meetup11 and agenda for meetup12
  docs/content.md
Labels: size/S, approved

#95 update agenda for Meetup 12
  docs/content.md
Labels: size/XS, approved

#94 Meetup blog
  docs/content/opfmeetup_blog_post1.md
  docs/content/opfmeetup_blog_post2.md
  docs/content/opfmeetup_blog_post3.md
Labels: approved, size/L

#99 Agenda for meetup 13
  docs/content.md
Labels: size/XS, approved
