Repository operate-first/operate-first-data-science-community, pull requests merged in 2022-03, with the labels that each got.

#39 Add the privacy policy for the Opf DS Community Meetup
  docs/privacy-policy.md
Labels: size/M, approved, lgtm

#53 Update agenda for meetup 7 and 8
  docs/content.md
  docs/content/opfmeetup7.pdf
  docs/meetup-landing-page.md
Labels: size/S, approved

#59 Added an data-collection notebook
  notebooks/data-collection.ipynb
Labels: approved, size/L, lgtm

#61 Update meetup-landing-page.md
  docs/meetup-landing-page.md
Labels: size/XS, approved

#63 Add slides pdf for meetup 5
  docs/content/opfmeetup5.pdf
Labels: size/XS, approved, lgtm

#64 Add slides pdf for opf ds meetup 3
  docs/content/opfmeetup3.pdf
Labels: size/XS, approved

#65 Add slides meetup 2
  docs/content/opfmeetup2.pdf
Labels: size/XS, approved

#68 meetup 8 slides
  docs/content/opfmeetup8.pdf
Labels: size/XS, approved

#60 EDA notebook for meet-up attendees obfuscated data
  Pipfile
  Pipfile.lock
  notebooks/EDA_meetup_attendees.ipynb
Labels: approved, lgtm, size/XXL

#71 Update agenda for meetup 8 and 9
  docs/content.md
Labels: size/M, approved, lgtm
