Repository operate-first/operate-first-data-science-community, pull requests merged in 2022-02, with the labels that each got.

#31 Add email templates
  docs/email_templates/invite_template.md
  docs/email_templates/postmeetup_update.md
Labels: size/M, approved

#32 Add sample attendees data
  data/raw/sample_data.csv
  notebooks/create_dataset.ipynb
Labels: approved, size/XL

#22 Add format for the meetup
  docs/format.md
Labels: size/M, approved, lgtm

#43 Update Agenda for meetup 6
  docs/content.md
Labels: size/S, approved, lgtm

#33 Added a notebook for exploring data obfuscation technique
  notebooks/data_obfuscation.ipynb
Labels: approved, size/XXL

#44 Add actionable items to the issue_template
  .github/ISSUE_TEMPLATE/event_template.md
  .github/ISSUE_TEMPLATE/topic_submission.md
Labels: size/M, approved

#48 Update Agenda
  docs/content.md
Labels: size/S, approved
