Repository operate-first/operate-first-data-science-community, pull requests merged in 2022-04, with the labels that each got.

#77 Update links for slides
  docs/content.md
Labels: size/S, approved, lgtm

#78 Meetup 9 slides
  docs/content.md
  docs/content/opfmeetup9.pdf
Labels: size/XS, approved

#79 EDA notebook update
  notebooks/EDA_meetup_attendees.ipynb
Labels: approved, size/L, lgtm

#80 Update agenda for meetup 9 video link
  docs/content.md
Labels: size/S, approved

#86 Update agenda for meetup10
  docs/content.md
Labels: size/XS, approved

#74 add q1 report
  docs/assets/image1.png
  docs/assets/image2.png
  docs/assets/image3.png
  docs/assets/image4.png
  docs/assets/image5.png
  docs/assets/image6.png
  docs/assets/image7.png
  docs/q1_report.md
Labels: size/M, approved, lgtm

#88 Update meetup#10 slides
  docs/content/opfmeetup10.pdf
Labels: size/XS, approved

#90 Update agenda for meetup 10 and 11
  docs/content.md
Labels: size/S, approved

#70 Update format to include youtube naming convention
  docs/format.md
Labels: size/XS, approved
